package com.shinowit.dao.mapper;

import com.shinowit.entity.Teacher;
import com.shinowit.entity.TeacherCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int countByExample(TeacherCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int deleteByExample(TeacherCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int insertSelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    List<Teacher> selectByExample(TeacherCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    Teacher selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int updateByExampleSelective(@Param("record") Teacher record, @Param("example") TeacherCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int updateByExample(@Param("record") Teacher record, @Param("example") TeacherCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int updateByPrimaryKeySelective(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbggenerated Sun Jan 11 16:49:43 CST 2015
     */
    int updateByPrimaryKey(Teacher record);

    List<Teacher> selectPage(TeacherCriteria example);

    Integer selectMaxPrimaryKeyValue();
}